### ISSUE TITLE
Can't install and execute akimous in Ubuntu container

### ISSUE THREAD

**Issue by Jaimecclin** [akimous/akimous#4]
Hi,

I used Ubuntu image to pip install it in container. But akimous can't be found.

```
ERROR: Could not find a version that satisfies the requirement akimous (from versions: none)
ERROR: No matching distribution found for akimous
```

Herewith the container system information:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
```

I also tried to pull image and run it on Windows Docker. It cannot be executed successfully. The following is error message:

```
[I 200405 04:07:47.705 __main__:35] Starting Akimous 0.8.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/akimous", line 5, in <module>
    from akimous.__main__ import start
  File "/usr/local/lib/python3.8/site-packages/akimous/__main__.py", line 41, in <module>
    from . import project
  File "/usr/local/lib/python3.8/site-packages/akimous/project.py", line 8, in <module>
    from git import InvalidGitRepositoryError, Repo
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

Any suggestion is welcome.

**Comment by red8012** [comment]
OK. There are actually two issues. The first one is the failure to install on Ubuntu 18.04. The other is the failure to start on Windows.

Here's my quick response to the first one, and I will investigate the second one later.

Akimous requires Python 3.7 or newer to work. So on Ubuntu 18.04, which comes with Python 3.6, it will fail during installation. If you are using images from Dockerhub, I suggest you either try the official [Akimous image](https://hub.docker.com/r/red8012/akimous) or the official [Python image](https://hub.docker.com/_/python), or use Ubuntu 19.10/20.04 instead.

**Comment by red8012** [comment]
The second issue is that it cannot find git on the system.
I tried to make it able to start even if git is unavailable. I'll test it tomorrow on Windows. Please have a test if you get some free time. Feel free to reopen this if there're still problems.
